# avec sudo ansible-playbook -c local config.vm1.yml
---
- hosts: localhost
  tasks:
      # adresse IPv6 avec nmcli (CLI pour NetworkManager)
      # Ã©ventuellement, pour supprimer les connexions en trop, faire
      # $ nmcli connection del ansible-eth1
#   - shell: ip -6 route delete default
   - shell: nmcli connection add ifname eth1 con-name eth1-LAN1 type ethernet ip4 172.16.2.132/28
   - shell: nmcli connection add ifname eth2 con-name eth2-LAN2 type ethernet ip4 172.16.2.162/28
   - shell: ip route delete default
     ignore_errors: True
   - shell: ip route delete default
     ignore_errors: True
   - shell: ip route delete default
     ignore_errors: True
   - shell: ip route delete default
     ignore_errors: True
   - shell: ip route add 172.16.2.128/28 dev eth1                   #-->LAN1
   - shell: ip route add 172.16.2.160/28 dev eth2                   #-->LAN2
   - shell: ip route add 172.16.2.144/28 via 172.16.2.131 dev eth1  #-->LAN3
   - shell: ip route add 172.16.2.176/28 via 172.16.2.163 dev eth2  #-->LAN4
   
   
